import type { Metadata } from "next";
import Head from "next/head";
import { Inter } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={inter.className}>
      <Head>
        <title>Wombat's Wondrous Trivia Time</title>
        <meta name="description" content="Trivia Fun for the whole family!" />
        <link rel="icon" href="/static/favicon.ico" sizes="any" />
      </Head>

      {children}
    </div>
  );
}
